{"errorMessage": "check_s3folder_exists function has an error", "errorType": "Exception", "stackTrace": ["  File \"/var/task/lambda_function.py\", line 22, in lambda_handler\n    if check_s3folder_exists(bucket,f'{prefix}/',f'{user_id}/'):\n", "  File \"/var/task/util.py\", line 50, in check_s3folder_exists\n    raise Exception(\"check_s3folder_exists function has an error\")\n"]}